version: "3.9"
services:
  postgres:
    image: eddhannay/alpine-postgres-temporal-tables:latest
    container_name: unbiased_postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - test_net
    volumes:
      - type: bind
        source: ./inst/postgres/
        target: /docker-entrypoint-initdb.d/
  api:
    image: unbiased
    container_name: unbiased_api
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - test_net
  tests:
    image: unbiased
    container_name: unbiased_tests
    depends_on:
      - api
    environment:
      - CI=true
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - test_net
    command: R -e "testthat::test_package('unbiased')"

networks:
  test_net:
