version: "3.9"
services:
  api:
    image: unbiased
    container_name: unbiased_api
    networks:
      - test_net
  tests:
    image: unbiased
    container_name: unbiased_tests
    depends_on:
      - api
    environment:
      - CI=true
    networks:
      - test_net
    command: R -e "testthat::test_package('unbiased')"

networks:
  test_net:
