version: "3.9"
services:
  api:
    image: unbiased
    container_name: unbiased_api
    environment:
      - CI=true
      - RENV_CONFIG_SANDBOX_ENABLED=false
    networks:
      - test_net
  tests:
    image: unbiased
    container_name: unbiased_tests
    depends_on:
      - api
    environment:
      - CI=true
      - RENV_CONFIG_SANDBOX_ENABLED=false
    networks:
      - test_net
    volumes:
      - type: bind
        source: ./tests
        target: /src/unbiased/tests
    command: Rscript tests/testthat.R

networks:
  test_net:
