version: "3.9"
services:
  db:
    image: postgres:16.0
    container_name: unbiased_db
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - test_net
    volumes:
      - type: bind
        source: ./inst/postgres/
        target: /docker-entrypoint-initdb.d/
  api:
    image: unbiased
    container_name: unbiased_api
    depends_on:
      - db
    networks:
      - test_net
  tests:
    image: unbiased
    container_name: unbiased_tests
    depends_on:
      - api
    environment:
      - CI=true
    networks:
      - test_net
    command: R -e "testthat::test_package('unbiased')"

networks:
  test_net:
