version: "3.9"
services:
  postgres:
    image: temporal_postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - test_net
  tests:
    # image: unbiased
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - CI=true
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - test_net
    command: R -e "install.packages('covr'); covr::package_coverage()"

networks:
  test_net:
